version: '3'
services:
    server:
        container_name: 'php-apache'
        image: php:apache
        volumes:
            - './:/var/www/html/'
        ports:
            - 80:80
# volumes:
#     triviaServer:
#         driver: local
